name: Deploy

on:
  push:
    branches: ["main"]

env:
  API_PORT: ${{secrets.API_PORT}}
  CLIENT_DOMAIN: ${{secrets.CLIENT_DOMAIN}}
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Updating Ubuntu system and Heroku
        run: sudo apt-get update && sudo apt-get install heroku
      - name: Login to Heroku Container registry
        run: heroku container:login
      - name: Build and push
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web
      - name: Release
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
