name: Test

on:
  push:
    branches: ["main", "develop"]

  pull_request:
    types: [opened]

env:
  API_PORT: 3500
  CLIENT_DOMAIN: http://localhost:3000/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - run: echo 'Finished :)'
